### ISSUE TITLE
1 array ipv 3

### ISSUE THREAD

**Issue by ninadepina** [Laurens256/web-app-from-scratch-2223#5]
https://github.com/Laurens256/web-app-from-scratch-2223/blob/9bae3d311584aeab9d0392d157cb4dce941ded0a/pokedex/scripts/loadList.ts#L15-L33

kan je niet beter een map function op de `listItems` gebruiken en daarna de `idField`, `nameField` en `typeSection` eruit halen, dan hoef je niet 3x 'dezelfde' map function uit te voeren

dus dat het dan zoiets word:
```typescript
const listItems = Array.from(pokemonList.children).map((listItem) => ({
	idField: listItem.querySelector('section:first-of-type p') as HTMLParagraphElement,
	nameField: listItem.querySelector('section:nth-of-type(2) h2') as HTMLHeadingElement,
	typeSection: listItem.querySelector('section:last-of-type') as HTMLElement
}));

const idField = listItems[i].idField;
const nameField = listItems[i].nameField;
const typeSection = listItems[i].typeSection;
```

**Comment by Laurens256** [comment]
holy moly je hoefde niet zo op me te flexen
