### ISSUE TITLE
shorter variable

### ISSUE THREAD

**Issue by ninadepina** [Laurens256/web-app-from-scratch-2223#8]
https://github.com/Laurens256/web-app-from-scratch-2223/blob/3f2d7241ceb48447624109d9de528148531b9cd2/scripts/views/detailView.ts#L118-L119

dit zou ook moeten werken:
```javascript
const [topSection, bottomSection] = Array.from(pokemonDetail.children) as HTMLElement[];
```

**Comment by Laurens256** [comment]
ik weet nou niet of dit heel veel beter is maar ziet er wel cool uit

**Comment by ninadepina** [comment]
Het oog wil ook wat hè
