### ISSUE TITLE
less css

### ISSUE THREAD

**Issue by ninadepina** [Laurens256/web-app-from-scratch-2223#9]
https://github.com/Laurens256/web-app-from-scratch-2223/blob/3f2d7241ceb48447624109d9de528148531b9cd2/styles/header-footer.css#L32-L33
```css
header ul li :is(h1, h2) {}
```

https://github.com/Laurens256/web-app-from-scratch-2223/blob/3f2d7241ceb48447624109d9de528148531b9cd2/styles/pokemon-list.css#L141-L142
```css
.pokemonlist li button:has(:hover, :focus) {}
```

**Comment by Laurens256** [comment]
werkt niet goed in Firefox

**Comment by Laurens256** [comment]
je zou trouwens ook beter `.pokemonlist li button:is(:hover, :focus) {}` kunnen doen
